### ISSUE TITLE
Tables uncentralized

### ISSUE THREAD

**Issue by EduardoLR10** [EduardoLR10/HRTRoutineProject#13]
When the entire table fits in the screen, it should be centralized.

**Comment by luigiminardim** [comment]
@EduardoLR10, can you show me an example where it happens?

**Comment by EduardoLR10** [comment]
Routine "Anemia Ferropriva"

**Comment by luigiminardim** [comment]
Has been fixed in the last

**Comment by luigiminardim** [comment]
The issue has been fixed in the latest commit in the dev-master branch.
