### ISSUE TITLE
Big Header titles are being hided.

### ISSUE THREAD

**Issue by luigiminardim** [EduardoLR10/HRTRoutineProject#15]
Some big headings are being hidden due to their size.

One can see it in the "Alimentação nos 2 Primeiros Anos de Vida", which is being converted to "Alimentação nos 2 Pri..."

**Comment by EduardoLR10** [comment]
An alternative to this is to provide the header the ability to dynamically change its size. Other option is to add enters when is necessary. The third option is a combination of the first 2 options.
