### ISSUE TITLE
Tags for search

### ISSUE THREAD

**Issue by EduardoLR10** [EduardoLR10/HRTRoutineProject#24]
Later in the line, the client will provide a list of words that are related to each routine. The search system needs to adress these words in the search process.

**Comment by luigiminardim** [comment]
Would be easier to achieve this goal if all the routines already have a static attribute "tags", which could be an array of strings.

```javascript
class SomeRoutine extends React.Component {
  title = "Some Routine"
  authors = "Luigi Minardi e Eduardo Lemos"
  tags = ["tag1", "tag2"]

  render = () => 
   ...
 }
```

**Comment by EduardoLR10** [comment]
I'll request the client to provide these words in this format to finish this issue.

**Comment by luigiminardim** [comment]
Search with tags is already implemented in such a way that, if the routine doesn't have a tag, the search just doesn't match with the routine by the tag.
