### ISSUE TITLE
Figures are broken

### ISSUE THREAD

**Issue by EduardoLR10** [EduardoLR10/HRTRoutineProject#6]
When the image is too big you are not able to see the entire image. It is mandatory to have horizontal scroll.

**Comment by luigiminardim** [comment]
I gonna put images min-width to be 100% inside figures, but, what is the best approach: Make images to have a scroll or fix the size?

**Comment by EduardoLR10** [comment]
Two options:
1 - Fix the size but allow zoom
2 - Size is not fixed and exists horizontal scroll.

**Comment by luigiminardim** [comment]
It has been fixed, although the fixes need to be pushed into master.
