### ISSUE TITLE
Italic in References

### ISSUE THREAD

**Issue by EduardoLR10** [EduardoLR10/HRTRoutineProject#70]
The client requested to remove the italic aspect in References. The text needs to be normal.

**Comment by luigiminardim** [comment]
This can already be done with the syntax:

```tsx
<Reference idx={0}> Normal text. <Italic>Italic Text</Italic></Reference>
```

**Comment by EduardoLR10** [comment]
In the routines' content, with only the attributes "key" and "body", it's not possible to format the text in the normal way. It is hard coded italic.

**Comment by luigiminardim** [comment]
@EduardoLR10, are you suggesting any other typography style or do you want to have a new attribute to control the typography style?

**Comment by EduardoLR10** [comment]
I'm suggesting to remove the italic aspect of the references, using only normal text instead.

**Comment by luigiminardim** [comment]
@EduardoLR10, do you want to keep the bold in the index?

**Comment by EduardoLR10** [comment]
The bold index can continue.
